### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by klaydev** [Fernthedev/ReportPlus#71]
I found a bug by the way. When you write / report <nickname>, after selecting a button in the GUI, you have to enter the reason in the chat, and so, the fact is that the reason fits, but each subsequent message creates a new report indicating the reason - this message.
Links:
https://hastebin.com/vojaroyeda.md
https://hastebin.com/hocavofali.md
https://hastebin.com/edudonaguf.md

**Comment by Fernthedev** [comment]
The second error is the same problem as the first. Try with commit build ced5501c577edd141877ff1b7f8716c75721362d. The compiled jar is in https://142-179760794-gh.circle-artifacts.com/0/jars/ReportPlus-7.5-pre4.jar

**Comment by klaydev** [comment]
Okay, close theme
